title: "Metin Zorlu"
name: "Buhara"
email: metinzorlu@msn.com
description: Kişisel Blog Sitesidir.

plugins:
  - jekyll-seo-tag
  - jekyll-feed

# jekyll-feed settings
feed:
  # Site başlığı
  title: "Your Awesome Title"
  # Sitenizin kısa açıklaması
  description: "Kişisel blog sayfası"
  # Feed dosyasının adı (isteğe bağlı)
  name: "feed.xml"

baseurl: ""
url: ""
twitter_username: deruni
github_username: mtnzorlu
youtube_username: deruni79

markdown: kramdown
kramdown:
input: GFM
syntax_highlighter: rouge
remote_theme: mtnzorlu/buhara

# navmenu
atitle: Hakkımda
aurl: /about
btitle: Çalışmalar
burl: /works
ctitle: Alıntı
curl: /quote
