title: "Metin Zorlu"
name: "Buhara"
email: metinzorlu@msn.com
description: Blog site

baseurl: ""
url: "/"
twitter_username: deruni
github_username: mtnzorlu
youtube_username: deruni79

markdown: kramdown
kramdown:
input: GFM
syntax_highlighter: rouge
remote_theme: mtnzorlu/buhara

# navmenu
atitle: Hakkımda
aurl: /about
btitle: Çalışmalar
burl: /works
ctitle: Alıntı
curl: /quote
