title: "Metin Zorlu"
name: "Buhara"
email: metinzorlu@msn.com
description: Şahsi Blog Sayfası

baseurl: ""
url: ""
twitter_username: deruni
github_username: mtnzorlu
youtube_username: deruni79


highlighter: rouge
markdown: Kramdown
remote_theme: mtnzorlu/buhara

# navmenu
atitle: Hakkımda
aurl: /about
btitle: Çalışmalar
burl: /works
ctitle: Alıntı
curl: /quote
